global using Core.Exceptions.Constants;
global using Core.Extensions;
global using Core.Interfaces;
global using Core.Base;
global using Microsoft.EntityFrameworkCore;
global using School.Domain.Entities;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;